# Generated by Django 5.0.2 on 2024-03-03 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Occasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=55, verbose_name="Название причины сбора"
                    ),
                ),
            ],
            options={
                "verbose_name": "Повод для сбора",
                "verbose_name_plural": "Поводы для сбора",
            },
        ),
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("amount", models.PositiveIntegerField(verbose_name="Сумма сбора")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/%Y/%M/%d", verbose_name="Обложка"
                    ),
                ),
                ("date_of_end", models.DateField(verbose_name="Дата завершения сбора")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор сбора",
                    ),
                ),
                (
                    "occasion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collects.occasion",
                        verbose_name="Причина сбора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сбор",
                "verbose_name_plural": "Сборы",
            },
        ),
    ]
